pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https.jitpack.io' }
    }
}
rootProject.name = "Nono Controller"
include ':app'

includeBuild('tmp/Android-BLE-Library-2.11.0')